# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Age', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
