# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_auto_20170921_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='TellAFriend',
        ),
        migrations.AlterModelTable(
            name='tellafriend',
            table='Friend',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
