# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_auto_20170921_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=255)),
                ('Age', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Feedback', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.RenameModel(
            old_name='TellAFriend',
            new_name='Friend',
        ),
    ]
