# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_auto_20170922_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Name',
            field=models.CharField(max_length=255),
        ),
    ]
