# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_auto_20170922_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=255)),
                ('To', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=255)),
                ('Departure', models.CharField(max_length=255)),
                ('Arrival', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
    ]
