# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=255)),
                ('To', models.CharField(max_length=255)),
                ('Fare', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Fares',
            },
        ),
    ]
