# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedbacks',
        ),
        migrations.AlterModelTable(
            name='feedbacks',
            table='Feedbacks',
        ),
    ]
