# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('From', models.CharField(max_length=255)),
                ('To', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=255)),
                ('Departure', models.CharField(max_length=255)),
                ('Arrival', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Reservations',
            },
        ),
    ]
