# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='Seats',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
